# Signup request
POST http://127.0.0.1:5000/api/signup
Content-Type: application/json

{
    "Email": "dasun@egmail.com",
    "Password": "0000",
    "F_name": "dasun",
    "L_name": "desh"
}

###

# Login request
POST http://127.0.0.1:5000/api/login
Content-Type: application/json

{
    "Email": "dasun@egmail.com",
    "Password": "0000"
}

###

# Get profile
GET http://127.0.0.1:5000/api/profile
Content-Type: application/json

###

# Update profile
PUT http://127.0.0.1:5000/api/profile
Content-Type: application/json

{
    "F_name": "sudheera",
    "L_name": "dinithi"
}

###

# Delete account
DELETE http://127.0.0.1:5000/api/profile
Content-Type: application/json

###

# Logout
POST http://127.0.0.1:5000/api/logout
Content-Type: application/json
